name: guardian_app
description: Parental Control Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.6.4
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.2
  local_auth: ^2.1.8
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  uuid: ^4.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
