"""
Tests for code generation artifacts produced by the multi-agent pipeline.
"""

from __future__ import annotations

import ast
import inspect
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest


def test_frontend_generator_module_is_substantial():
    from src.agents import frontend_generator
    src = Path(frontend_generator.__file__).read_text(encoding="utf-8")
    assert len(src.splitlines()) > 100
    assert "class FrontendGenerator" in src
    assert "generate_component" in src or "generate_page" in src


def test_backend_generator_module_is_substantial():
    from src.agents import backend_generator
    src = Path(backend_generator.__file__).read_text(encoding="utf-8")
    assert len(src.splitlines()) > 100
    assert "class BackendGenerator" in src
    assert "generate_route" in src or "generate_model" in src


def test_integration_generator_module_is_substantial():
    from src.agents import integration_generator
    src = Path(integration_generator.__file__).read_text(encoding="utf-8")
    assert len(src.splitlines()) > 100
    assert "class IntegrationGenerator" in src


def test_frontend_generator_can_instantiate_with_project(tmp_path):
    from src.agents.frontend_generator import FrontendGenerator
    from src.core.workspace import Project

    project = Project(
        id="test", name="test", description="test",
        root_dir=str(tmp_path), tech_stack={"frontend": "nextjs"},
        target="web", profile_id=1,
    )
    gen = FrontendGenerator(project=project)
    assert gen is not None
    # Prefer generate_component if available
    if hasattr(gen, "generate_component"):
        from src.agents.frontend_generator import ComponentSpec
        spec = ComponentSpec(name="HelloCard", type="component", description="A hello card")
        result = gen.generate_component(spec)
        assert result is not None
        text = " ".join(str(v) for v in (result.values() if isinstance(result, dict) else [result]))
        assert len(text) > 10


def test_backend_generator_can_instantiate_with_project(tmp_path):
    from src.agents.backend_generator import BackendGenerator, RouteSpec
    from src.core.workspace import Project

    project = Project(
        id="test", name="test", description="test",
        root_dir=str(tmp_path), tech_stack={"backend": "fastapi"},
        target="web", profile_id=1,
    )
    gen = BackendGenerator(project=project)
    assert gen is not None
    if hasattr(gen, "generate_route"):
        spec = RouteSpec(path="/api/health", method="GET", name="health", description="Health check")
        result = gen.generate_route(spec)
        assert result is not None
        text = " ".join(str(v) for v in (result.values() if isinstance(result, dict) else [result]))
        assert len(text) > 10


@pytest.mark.asyncio
async def test_pipeline_writes_artifacts_to_disk(tmp_path):
    """Full pipeline (mocked NIM) must write non-empty files under project_dir."""
    from backend.agent_pipeline import AgentPipeline

    mock = AsyncMock()

    async def fake_stream(messages, model=None, temperature=0.4, max_tokens=4096):
        system = (messages[0].get("content") or "") if messages else ""
        user = (messages[1].get("content") or "") if len(messages) > 1 else ""
        blob = (system + " " + user).lower()
        if "plan" in blob or "architect" in blob:
            yield "# Plan\n\nTech stack: Next.js + FastAPI + Postgres\n"
        elif "design" in blob:
            yield "# Design\n\nColors: primary #76B900\n"
        elif "frontend" in blob or "react" in blob:
            yield "export default function App() { return <div>Hello</div>; }\n"
        elif "backend" in blob or "fastapi" in blob:
            yield "from fastapi import FastAPI\napp = FastAPI()\n@app.get('/health')\ndef health(): return {'ok': True}\n"
        elif "docker" in blob or "integration" in blob:
            yield "version: '3.8'\nservices:\n  web:\n    image: node:20\n"
        else:
            yield "# artifact\ncontent generated by agent\n"

    mock.chat_stream = fake_stream
    mock.list_models = AsyncMock(return_value=[MagicMock(id="meta/llama-3.1-8b-instruct")])
    mock.health_check = AsyncMock(return_value={"ready": True, "live": True})
    mock.close = AsyncMock()

    pipeline = AgentPipeline(mock)
    ctx = await pipeline.run(
        user_prompt="Build a simple hello SaaS with health endpoint",
        project_dir=str(tmp_path),
    )

    assert ctx is not None
    files = [p for p in tmp_path.rglob("*") if p.is_file()]
    assert len(files) >= 1, f"Expected generated files, found {files}"
    for f in files:
        assert f.stat().st_size > 0, f"{f} is empty"


def test_agent_pipeline_module_imports():
    from backend.agent_pipeline import AgentPipeline, PipelineStatus
    assert PipelineStatus.COMPLETE.value == "complete"
    assert inspect.isclass(AgentPipeline)
