@echo off
setlocal EnableExtensions EnableDelayedExpansion

echo === Codex CLI + NVIDIA NIM (GLM-5.2) Setup ===
echo.

:: ---------------------------------------------------------------------------
:: Prerequisites
:: ---------------------------------------------------------------------------
where node >nul 2>nul
if errorlevel 1 (
    echo [ERROR] Node.js not found on PATH.
    echo         Install LTS from https://nodejs.org/ then re-open this terminal.
    pause
    exit /b 1
)
where npm >nul 2>nul
if errorlevel 1 (
    echo [ERROR] npm not found on PATH.
    pause
    exit /b 1
)

:: ---------------------------------------------------------------------------
:: Step 1: Install / update Codex CLI
:: ---------------------------------------------------------------------------
echo [1/5] Installing Codex CLI globally...
call npm install -g @openai/codex
if errorlevel 1 (
    echo [ERROR] npm install failed.
    echo         Try an elevated prompt ^(Run as administrator^) or fix npm permissions.
    pause
    exit /b 1
)

where codex >nul 2>nul
if errorlevel 1 (
    echo [WARN] codex not on PATH yet. You may need to restart the terminal after npm global install.
) else (
    for /f "tokens=*" %%V in ('codex --version 2^>nul') do echo       Found: %%V
)

:: ---------------------------------------------------------------------------
:: Step 2: Codex config directory
:: ---------------------------------------------------------------------------
echo [2/5] Preparing %%USERPROFILE%%\.codex ...
set "CODEX_DIR=%USERPROFILE%\.codex"
if not exist "%CODEX_DIR%" mkdir "%CODEX_DIR%"

:: ---------------------------------------------------------------------------
:: Step 3: API key (never written into config.toml)
:: ---------------------------------------------------------------------------
echo [3/5] NVIDIA API key
echo       Get a key from https://build.nvidia.com/
echo.
if defined NVIDIA_NIM_API_KEY (
    echo       Existing NVIDIA_NIM_API_KEY is already set in this session.
    set /p REUSE="       Reuse it? [Y/n]: "
    if /i "!REUSE!"=="n" set "NVIDIA_NIM_API_KEY="
)
if not defined NVIDIA_NIM_API_KEY (
    set /p NVIDIA_NIM_API_KEY="       Paste NVIDIA API key: "
)
if not defined NVIDIA_NIM_API_KEY (
    echo [ERROR] No API key provided.
    pause
    exit /b 1
)
:: trim simple spaces
set "NVIDIA_NIM_API_KEY=!NVIDIA_NIM_API_KEY: =!"

:: ---------------------------------------------------------------------------
:: Step 4: Write correct config.toml
::   Root keys BEFORE tables (TOML requirement).
::   Use model_providers.<id> + env_key (not api_key = "env:...").
::   NVIDIA NIM is OpenAI Chat Completions compatible -> wire_api = "chat".
:: ---------------------------------------------------------------------------
echo [4/5] Writing "%CODEX_DIR%\config.toml" ...

(
echo # Codex CLI — NVIDIA NIM provider
echo # Generated by setup_codex_nvidia.bat
echo.
echo model = "z-ai/glm-5.2"
echo model_provider = "nvidia"
echo.
echo # Optional agent defaults ^(adjust as you like^)
echo approval_policy = "on-request"
echo sandbox_mode = "workspace-write"
echo.
echo [model_providers.nvidia]
echo name = "NVIDIA NIM"
echo base_url = "https://integrate.api.nvidia.com/v1"
echo env_key = "NVIDIA_NIM_API_KEY"
echo wire_api = "chat"
) > "%CODEX_DIR%\config.toml"

if not exist "%CODEX_DIR%\config.toml" (
    echo [ERROR] Failed to write config.toml
    pause
    exit /b 1
)
echo       Wrote %CODEX_DIR%\config.toml

:: ---------------------------------------------------------------------------
:: Step 5: Environment variables
::   setx = permanent for FUTURE terminals
::   set  = current session so you can test immediately
:: ---------------------------------------------------------------------------
echo [5/5] Setting environment variables...

set "NVIDIA_NIM_API_KEY=!NVIDIA_NIM_API_KEY!"
set "NIM_API_KEY=!NVIDIA_NIM_API_KEY!"
set "NVIDIA_API_KEY=!NVIDIA_NIM_API_KEY!"

setx NVIDIA_NIM_API_KEY "!NVIDIA_NIM_API_KEY!" >nul
setx NIM_API_KEY "!NVIDIA_NIM_API_KEY!" >nul
setx NVIDIA_API_KEY "!NVIDIA_NIM_API_KEY!" >nul

echo.
echo === Setup complete ===
echo.
echo Config:   %CODEX_DIR%\config.toml
echo Provider: nvidia  ^(https://integrate.api.nvidia.com/v1^)
echo Model:    z-ai/glm-5.2
echo Env key:  NVIDIA_NIM_API_KEY  ^(also NIM_API_KEY / NVIDIA_API_KEY for Neon^)
echo.
echo Next:
echo   1. Prefer a NEW terminal so setx values are always visible.
echo   2. cd into your project ^(e.g. neon_unified^) so AGENTS.md is picked up.
echo   3. Run:  codex
echo   4. Optional check: codex exec "Reply with exactly: NIM_OK"
echo.
echo If requests fail with protocol errors, open config.toml and try:
echo   wire_api = "responses"
echo instead of "chat" ^(depends on Codex version / endpoint support^).
echo.
pause
endlocal
